#!/bin/bash

export LAB=lab5

(make clean; make) || exit 1

total=0
totalmax=0

rm -f total.txt *out total.txt

# Test driver
function runtest {
  prog=$1
  args=$2
  testinput=$3
  grade=$4
  totalmax=`expr $totalmax + $grade`;
  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="$prog $args $inputdescr"
  
  echo "======= $descr ==========="

  #Run tested program
  ./$prog $args < $testinput > $prog.out
  ./$prog.org $args< $testinput > $prog.org.out
  diff $prog.out $prog.org.out > diff.out
  if [ $? -eq 0 ]; then
      cat $prog.out
      echo Test passed...;
      printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
      total=`expr $total + $grade`;
  else
      echo "*****Test Failed*****";
      echo ------ Your Output ----------
      cat $prog.out
      echo ------ Expected Output ------
      cat $prog.org.out
      echo ------ Difference -----------
      cat diff.out
      echo -----------------------------
      printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
  fi
  echo
}

# List of tests running
runtest test_mystring "test1" none 5
runtest test_mystring "test2" none 5
runtest test_mystring "test3" none 5
runtest test_mystring "test4" none 10
runtest test_slist "test1" none 5
runtest test_slist "test2" none 5
runtest test_slist "test3" none 5
runtest test_slist "test4" none 10
runtest isbalanced "[]" none 2
runtest isbalanced "[][" none 2
runtest isbalanced "[]]" none 2
runtest isbalanced "[)" none 2
runtest isbalanced "[]{()}" none 4
runtest isbalanced "[]{()()}" none 4
runtest isbalanced "({)}" none 4 
runtest isbalanced "([{)]}" none 4
runtest isbalanced "]" none 1
runtest countwords test.txt none 10
runtest countwords cosmos.txt none 15
runtest test_mysort "test1" none 4
runtest test_mysort "test2" none 4
runtest test_mysort "test3" none 4
runtest test_mysort "test4" none 4
runtest test_mysort "test5" none 4
runtest test_bits "test1" none 4
runtest test_bits "test2" none 4
runtest test_bits "test3" none 4
runtest test_bits "test4" none 4
runtest test_bits "test5" none 4


./check-strfunc.sh
if [ $? -eq 0 ]; then
  echo
else
  total=`expr $total - 20`;
  echo "Don't use string library in mystring.c (-20pts)" >>  total.txt
fi

echo
echo
echo   "-------------------------------------------------"
echo   "CS240: $LAB. $USER   "
echo   "-------------------------------------------------"
cat total.txt
echo   "-------------------------------------------------"
echo   "CS240: $LAB. $USER" `date` " Total: " $total of $totalmax >> total.out
echo >> total.out

cat total.out
cat total.out >> .local.total.out

#Do not remove or comment these lines. They are used for monitoring progress.
labout=/homes/cs240/LABOUT/$LAB/$USER/total.txt
cat total.out >> $labout
git add -A  >> .local.git.out
git commit -a -m "$total of $totalmax" >> .local.git.out




