#!/usr/bin/expect -f

puts "=========== Running Test 3 ============"

source testing.tcl

set timeout 2
spawn ../high-low
match_max 100000

myexpect "Welcome to the High Low game...\r
Think of a number between 1 and 100 and press press <enter>"
send -- "\r"
myexpect "\r
Is it higher than 50? (y/n)\r
"
send -- "x\r"
myexpect "x\r
Type y or n\r
Is it higher than 50? (y/n)\r
"
send -- "x\r"
myexpect "x\r
Type y or n\r
Is it higher than 50? (y/n)\r
"
send -- "t\r"
myexpect "t\r
Type y or n\r
Is it higher than 50? (y/n)\r
"
send -- "y\r"
myexpect "y\r
Is it higher than 75? (y/n)\r
"
send -- "y\r"
myexpect "y\r
Is it higher than 88? (y/n)\r
"
send -- "n\r"
myexpect "n\r
Is it higher than 81? (y/n)\r
"
send -- "n\r"
myexpect "n\r
Is it higher than 78? (y/n)\r
"
send -- "y\r"
myexpect "y\r
Is it higher than 79? (y/n)\r
"
send -- "y\r"
myexpect "y\r
Is it higher than 80? (y/n)\r
"
send -- "y\r"
myexpect "y\r
\r
>>>>>> The number is 81\r
\r
Do you want to continue playing (y/n)?"
send -- "n\r"
myexpect eof

puts ">>>>>> Test3 passed"
exit 0
