#!/usr/bin/expect -f

puts "=========== Running Test 4 ============"

source testing.tcl

set timeout 2
spawn ../high-low
match_max 100000

myexpect  "Welcome to the High Low game...\r
Think of a number between 1 and 100 and press press <enter>"
send -- "\r"
myexpect  "\r
Is it higher than 50? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
Is it higher than 25? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
Is it higher than 12? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
Is it higher than 6? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
Is it higher than 3? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
Is it higher than 1? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
\r
>>>>>> The number is 1\r
\r
Do you want to continue playing (y/n)?"
send -- "y\r"
myexpect  "y\r
Think of a number between 1 and 100 and press press <enter>"
send -- "\r"
myexpect  "\r
Is it higher than 50? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 75? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 88? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 94? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 97? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 99? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 100? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
\r
>>>>>> The number is 101\r
\r
Do you want to continue playing (y/n)?"
send -- "n\r"
myexpect eof

puts ">>>>>> Test4 passed"
exit 0
