#!/usr/bin/expect -f

puts "=========== Running Test 1 ============"

source testing.tcl

set timeout 2
spawn ../high-low
match_max 100000

myexpect "Welcome to the High Low game...\r
Think of a number between 1 and 100 and press press <enter>" 
send -- "\r"
myexpect  "\r
Is it higher than 50? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
Is it higher than 25? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 37? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 43? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
Is it higher than 40? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
Is it higher than 38? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 39? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
\r
>>>>>> The number is 39\r
\r
Do you want to continue playing (y/n)?"
send -- "n\r"
myexpect eof

puts ">>>>>> Test1 passed"
exit 0


