#!/bin/sh

(cd .. && make)

grade0=0
grade0max=40
(echo "---- Test 0 -----" &&cd .. && ./grade-gdb $USER) && grade0=`expr $grade0 "+" 40`

grade1=0
grade1max=5
../testmemdump 1 && grade1=`expr $grade1 "+" 5`

grade2=0
grade2max=5
../testmemdump 2 && grade2=`expr $grade2 "+" 5`

grade3=0
grade3max=5
../testmemdump 3 && grade3=`expr $grade3 "+" 5`

grade4=0
grade4max=5
../testmemdump 4 && grade4=`expr $grade4 "+" 5`

grade5=0
grade5max=5
../testmemdump 5 && grade5=`expr $grade5 "+" 5`

grade6=0
grade6max=5
../testmemdump 6 && grade6=`expr $grade6 "+" 5`

total=`expr $grade0 + $grade1 + $grade2 + $grade3 + $grade4 + \
      $grade5 + $grade6 `

totalmax=`expr $grade0max + $grade1max + $grade2max + $grade3max + \
      $grade4max + $grade5max + $grade6max `

echo   "-------------------------------------------------"
echo   "User:  $1 "
echo   "-------------------------------------------------"
printf "./grade-gdb $USER      	 %-3d%s%-3d\n" $grade0 " of " $grade0max
printf "./testmemdump 1:       	 %-3d%s%-3d\n" $grade1 " of " $grade1max
printf "./testmemdump 2:       	 %-3d%s%-3d\n" $grade2 " of " $grade2max
printf "./testmemdump 3:       	 %-3d%s%-3d\n" $grade3 " of " $grade3max
printf "./testmemdump 4:       	 %-3d%s%-3d\n" $grade4 " of " $grade4max
printf "./testmemdump 5:       	 %-3d%s%-3d\n" $grade5 " of " $grade5max
printf "./testmemdump 6:       	 %-3d%s%-3d\n" $grade6 " of " $grade6max
echo   "--------------------------------------------------"
printf "Total:                   %-3d%s%-3d\n" $total " of " $totalmax

