#!/bin/bash

(make clean; make) || exit 1

LAB=lab3b
total=0
totalmax=0

rm -f total.txt *out total.txt

# Test driver
function runtest {
  prog=$1
  args=$2
  testinput=$3
  grade=$4
  totalmax=`expr $totalmax + $grade`;

  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="./$prog $args $inputdescr"
  
  echo "========== $descr ==========="

  #Run tested program
  ./$prog $args < $testinput > $prog.out 

  #Run original program
  ./$prog.org $args< $testinput > $prog.org.out 

  diff $prog.out $prog.org.out > diff.out
  if [ $? -eq 0 ]; then
      cat $prog.out
      echo Test passed...;
      printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
      total=`expr $total + $grade`;
  else
      echo "*****Test Failed*****";
      echo ------ Your Output ----------
      cat $prog.out
      echo ------ Expected Output ------
      cat $prog.org.out
      echo ------ Difference -----------
      cat diff.out
      echo -----------------------------
      printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
  fi
  echo
}

# List of tests running
runtest convert "" none 1
runtest convert "10" none 1
runtest convert "10 10" none 1
runtest convert "10 10" none 1
runtest convert "10 10 10" none 1
runtest convert "16 10 FF" none 1
runtest convert "16 10 100" none 1
runtest convert "10 8 20" none 1
runtest convert "10 2 127" none 1
runtest convert "10 16 8191" none 1
runtest convert "10 25 100077900" none 1
runtest convert "2 16 100010001111" none 1
runtest convert "5 10 1234" none 1
runtest convert "5 10 123456" none 1

echo > total.out
echo >> total.out
echo   "-------------------------------------------------" >> total.out
echo   "CS240: $LAB . $USER   " >> total.out
date >> total.out
echo   "-------------------------------------------------" >> total.out
cat total.txt >> total.out >> total.out 
echo   "-------------------------------------------------" >> total.out 
echo   "CS240: $LAB. $USER" `date` " Total: " $total of $totalmax >> total.out
echo >> total.out

cat total.out
cat total.out >> .local.total.out

#Do not remove or comment these lines. They are used for monitoring progress.
labout=/homes/cs240/LABOUT/$LAB/$USER/total.txt
cat total.out >> $labout
git commit -a -m "$total of $totalmax" > git.out

